apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular
  labels:
    app: angular
spec:
  replicas: 1
  template:
    metadata:
      name: angular
      labels:
        app : angular
    spec:
      containers:
        - name: angular
          image: lisno/fronted:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: angular
