apiVersion : apps/v1
kind: Deployment
metadata:
  name: "angular"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "angular"
  template:
    metadata:
      labels:
        app: "angular"
    spec:
      containers:
        - name: "angular"
          image: "containerregistry48.azurecr.io/micro"
          ports:
          - containerPort: 80
