apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "micro-156d"
  labels:
    app: "micro-156d"
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
spec:
  rules:
    - host: old.b199c1c52ede48eb94fb.eastus2.aksapp.io
      http:
        paths:
          - path: /api/v1/finance
            pathType: Prefix
            backend:
                serviceName: angular
                port:
                  number: 80
    - host: b199c1c52ede48eb94fb.eastus2.aksapp.io
      http:
        paths:
          - path: /api/v1/finance
            pathType: Prefix
            backend:
                serviceName: finance
                port:
                  number: 9001
          - path: /api/v1/interior
            pathType: Prefix
            backend:
                serviceName: interior
                port:
                  number: 8080
          - path: /
            backend:
              serviceName: "micro-156d"
              servicePort: 80
